const BASE_URL = process.env.REACT_APP_API_KEY;
const IMAGES_URL = process.env.REACT_APP_UNSPLASH_IMAGES_API;
const UNSPLASH_TOKEN = process.env.REACT_APP_UNSPLASH_TOKEN;

const TEAM = '4-6';

export { BASE_URL, IMAGES_URL, UNSPLASH_TOKEN, TEAM };
